const thirdString = document.getElementById('string-3')
console.log(thirdString)
const fifthString = document.getElementById('string-5')
console.log(fifthString)
const secondString = document.getElementById('string-2')
console.log(secondString)
const sixthString = document.getElementById('string-6')
console.log(sixthString)
const fourthString = document.getElementById('string-4')
console.log(fourthString)
const firstString = document.getElementById('string-1')
console.log(firstString)

